### ISSUE TITLE
Request to get test_listfile.csv and val_listfile.csv

### ISSUE THREAD

**Issue by AmudhaTK** [nyuad-cai/MedFuse#1]
hi, I am doing project with your datasets.  I cannot able to get the mimic_iv_extracted folder , because i need test_listfile.csv and val_listfile.csv. Can you please lead me how to get those files for my work?

**Comment by farahshamout** [comment]
@AmudhaTK Please follow the steps here to generate the splits for MIMIC-IV: https://github.com/nyuad-cai/MedFuse/blob/main/mimic4extract/README.md
