### ISSUE TITLE
Needs clarity in runing the shell script

### ISSUE THREAD

**Issue by AmudhaTK** [nyuad-cai/MedFuse#11]
Hi @farahshamout,
 I can understand the situation of not sharing the original protected datasets. But with your help I come to know how to get preprocessed data from raw datasets. After getting proper system up-gradation, I started downloading the raw data from MIMIC IV and MIMIC-CXR-JPG. Thank you for the proper guidance on the memory needed to download the data. 

Now, I am working on the processing of the raw data. I did MIMIC IV data extraction using MIMIC III. I need clarification on this part.
 
Kindly help me with the details of the output that we can get after the execution of this Shell script:

# train the imaging model with 14 radiology labels.
sh ./scripts/radiology/uni_cxr.sh
# train LSTM model on extracted time-series EHR data for phenotype task.
sh ./scripts/phenotyping/train/uni_all.sh

# train LSTM model for the in-hospital-mortality task
sh ./scripts/mortality/train/uni_all.sh

It is showing error,as needs two positional arguments.
Which arguments I should pass to run the shell script?
It would be helpful to know the proper output of the above command. 

thank you,
Amudha T K

**Comment by ShazaElsharief** [comment]
Hi Amudha, you should be able to execute the scripts as specified in this step:

```
# train the imaging model with 14 radiology labels.
sh ./scripts/radiology/uni_cxr.sh
# train LSTM model on extracted time-series EHR data for phenotype task.
sh ./scripts/phenotyping/train/uni_all.sh

# train LSTM model for in-hospital-mortality task
sh ./scripts/mortality/train/uni_all.sh
```
without additional arguments. Please make sure that you have specified the cxr and ehr data directories before running the scripts, following the steps outlined in the README file.
