### ISSUE TITLE
About the ICD mapping in the phenotype classification task 

### ISSUE THREAD

**Issue by mhxu1998** [nyuad-cai/MedFuse#14]
Thank you for your work first, which has been a great inspiration to me.
I have noticed that "we mapped all ICD-10 codes to ICD-9 using the guidelines provided by the Centers for Medicare & Medicaid Services1, and then map them to CCS categories" was mentioned in section 4.1 Datasets and Benchmark Tasks. But I did not find the relevant content in the code. May I ask how it is implemented here?

**Comment by ShazaElsharief** [comment]
Hi, please refer to ./mimic4extract/resources directory.  You will find there the icd_9_10_definitions_2.yaml and the hcup_ccs_2015_definitions.yaml files to see how the mapping is done.
