### ISSUE TITLE
needs help in running the shell scripts

### ISSUE THREAD

**Issue by AmudhaTK** [nyuad-cai/MedFuse#16]
Dear @farahshamout ,
Hope you are doing well.

I need help in running the shell scripts.
sh ./scripts/phenotype/uni_csr.sh

sh ./scripts/mortality/train/uni_all.sh

It is showing an error, as it needs two positional arguments.
Do you know which arguments I should pass to run the shell script?
It would be helpful to know the proper output of the above command.

thank you,
Amudha T K

**Comment by ShazaElsharief** [comment]
Hi Amudha, you should be able to execute the scripts as specified in this step:

```
# train the imaging model with 14 radiology labels.
sh ./scripts/radiology/uni_cxr.sh
# train LSTM model on extracted time-series EHR data for phenotype task.
sh ./scripts/phenotyping/train/uni_all.sh

# train LSTM model for in-hospital-mortality task
sh ./scripts/mortality/train/uni_all.sh
```
without additional arguments. Please make sure that you have specified the cxr and ehr data directories before running the scripts, following the steps outlined in the README file.
