### ISSUE TITLE
About the stage1 checkpoints

### ISSUE THREAD

**Issue by Eldo-rado** [nyuad-cai/MedFuse#19]
Hi! @ShazaElsharief 

Thanks for your contribution, great work!
Could you please share the checkpoints of stage1 modality-specific encoders?

Thanks a lot.

**Comment by ShazaElsharief** [comment]
Hi @Eldo-rado, the checkpoints for the pretrained encoders are now updated under the MedFuse/checkpoints directory:

- CXR: checkpoints/cxr_rad_full
- Mortality: checkpoints/mortality/uni_ehr_all
- Phenotyping: checkpoints/phenotyping/uni_ehr_full
