### ISSUE TITLE
Need to know about both storage space and execution of the code for MedFuse

### ISSUE THREAD

**Issue by AmudhaTK** [nyuad-cai/MedFuse#4]
Hi @farahshamout ,
May i know how much memory is needed for the dataset storage + for the execution of the program (to Run the code)? So that I can request my institution for the same. {MedFuse}

**Comment by farahshamout** [comment]
Hi Amudha, 

- Raw MIMIC-CXR = I'm unsure please check here https://physionet.org/content/mimic-cxr-jpg/
- Resized MIMIC-CXR to 224x224 = 11 GB
- Raw MIMIC-IV = 65 GB
- Processed MIMIC-IV according to MedFuse for the prediction tasks = 21 GB

Instructions to get the resized images and the processed MIMIC-IV can be found in the README file
