### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by farazBhatti** [nyuad-cai/MedFuse#5]
Hi, are you planning to release pre-trained model along with sample dataset for inference and validation purposes? 
Thanks...

**Comment by AmudhaTK** [comment]
HI farazBhatti , yeah..kind of but you have done this using Linux environment. I am planning to do with windows (Colab) .
I was planning to get the image data and its associated clinical information of the patient. It would be helpful, if I could get them.
Can I  know the dataset +Implementaion memory capacity?

Thanks

**Comment by farahshamout** [comment]
Hi @farazBhatti we released the checkpoints for phenotyping, please find them here: https://github.com/nyuad-cai/MedFuse/tree/main/checkpoints/phenotyping

Please note that the dataset needs to be downloaded from the original database and we cannot provide samples ourselves.
