### ISSUE TITLE
Need of the Processed data from MedFuse.

### ISSUE THREAD

**Issue by AmudhaTK** [nyuad-cai/MedFuse#7]
Hi @farahshamout ,

I tried to extract the data which you mentioned in the ReadMe file of Github. while extracting, my system gets struck up. During our discussion through email, you mentioned that you had preprocessed data from MIMIC-CXR and MIMIC-IV, Can you please share it for my work?

**Comment by farahshamout** [comment]
Can you provide more details on what kind of problem you encountered? Unfortunately we cannot share the processed data, as it requires access to the original protected datasets.

**Comment by AmudhaTK** [comment]
> 
 Due to low system configuration, unfortunately, the download fails intermittently, which I tried many times. 
I understand your concern. Recently, I have been certified with MIT, CITI-data use Agreement through physionet. Please share the processed data, which will be helpful tin proceeding forward with my research work.

**Comment by AmudhaTK** [comment]
Due to low system configuration, unfortunately, the download fails intermittently, which I tried many times.
I understand your concern. Recently, I have been certified with MIT, CITI-data use Agreement through physionet. Please share the processed data, which will be helpful tin proceeding forward with my research work.
